# Generated by Django 4.0.5 on 2022-07-03 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('category', models.TextField(choices=[('other', 'разное'), ('bred', 'хлебо-булочные'), ('milk', 'молочка'), ('alco', 'алкоголь')], default='other', max_length=30)),
                ('remain', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
