# Generated by Django 4.0.5 on 2022-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.PositiveIntegerField(),
        ),
    ]
