# Generated by Django 4.0.5 on 2022-07-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_remain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proinbaskets', to='webapp.product', verbose_name='Продукт')),
            ],
        ),
    ]
