# Generated by Django 4.0.5 on 2022-08-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_order_orderbasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
